### ISSUE TITLE
live streaming

### ISSUE THREAD

**Issue by josefhernandez** [Vanilagy/mp4-muxer#14]
How can I do live streaming?

According to the documentation
`StreamTarget is not intended for live-streaming`

**Comment by Vanilagy** [comment]
You can't do live streaming. Streaming requires fMP4 (fragmented MP4), which this library doesn't implement. If there's enough demand, I might get to it sometime.

**Comment by josefhernandez** [comment]
Perhaps it would be better to let the issue open and let other vote on it

**Comment by Vanilagy** [comment]
Live-streaming works now in v4.0.0, which adds support for fragmented MP4! 🎉

**Comment by LiubomyrB** [comment]
@Vanilagy I tried to stream fragmented mp4 via ffmpeg to RTMP endpoint (FB). It works but the question is next.  I send chunks from mp4-muxer via web-socket to the server where ffmpeg pushes it to RTMP. The problem is that if a user disconnects for a few seconds and then reconnects, new ffmpeg process crashes with the next message:
```
4-_7jvKO8cvEF-_XAAAF FFmpeg STDERR: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d798c050c0] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d798c050c0] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d798c050c0] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d798c050c0] error reading header

4-_7jvKO8cvEF-_XAAAF FFmpeg STDERR: pipe:: Invalid data found when processing input

4-_7jvKO8cvEF-_XAAAF FFmpeg STDIN Error Error: write EPIPE
```
Ffmpeg crashes probably because I didn't pass the first chunk that was produced by mp4-muxer to the new ffmpeg process. As I understand, the first chunk contains some metadata like moov box that ffmpeg needs. So the question is: can I start (resume) streaming with ffmpeg again if the first chunk that I passed to init ffmpeg is not the first chunk that was produced by mp4-muxer. Does the first chunk really matter? Is it possible to prepend the required metadata (that only the first chunk contains) to each fmp4 chunk?

**Comment by Vanilagy** [comment]
@LiubomyrB I generally don't want to debug other people's application issues. But you shouldn't start a new ffmpeg process just because the connection terminates. When the connection comes back, you just send all chunks over that you haven't sent yet (or rather, that the other side hasn't received yet). If you're forced to restart the entire thing, then the client needs to keep a buffer of all previous chunks to restart the process.
