### ISSUE TITLE
Timestamps must be monotonically increasing. 

### ISSUE THREAD

**Issue by khuramhaf** [Vanilagy/mp4-muxer#25]
Dear Sir, 
I am designing a video editor in JavaScript. I am a using your library which is awesome anyhow some times while using large files I am facing the following error

"Timestamps must be monotonically increasing. 
Muxer.validateTimestamp_fn (mp4-muxer.js:1088:13)"

I am not sure if it is a bug or my coding error. I tried to fix this error a lot but could not succeed in fixing it. 
You can see the code by clicking following link.
https://github.com/khuramhaf/Video-Editor

The code is open source and I shall be thankful to you if you kindly help me in fixing the error.

**Comment by Vanilagy** [comment]
The "Timestamps must be monotonically increasing" error is thrown when you add a media chunk that has a smaller timestamp than the previous one. Since it doesn't make sense to go "back in time", the library prevents you from doing this by throwing an error.

There might be an issue with your timestamp logic. You should try logging every frame you encode and seeing when the timestamps start going backwards.

**Comment by khuramhaf** [comment]
Thanks for your reply. I reviewed my timestamps and found that decoder is
changing the timestamps. Any how I found another solution to the problem. I
really want to thank you for such a great library and I will surely sponsor
ur project whenever things starts working for me.

**Comment by Vanilagy** [comment]
Awesome, that's nice to hear! Can I close this issue? :)
