### ISSUE TITLE
Can I convert WebM videos into mp4?

### ISSUE THREAD

**Issue by nuthinking** [Vanilagy/mp4-muxer#37]
I record videos in WebM using `MediaRecorder`. I wonder if, perhaps with the combination of `VideoDecoder`, it would be possible to re-encode them into mp4 file without having to use ffmpeg for the conversion. 🤔

**Comment by nuthinking** [comment]
Currently looking for an webm-demuxer....

**Comment by Vanilagy** [comment]
A `webm-demuxer` would be the cleanest solution, but this should still be somewhat possible even without FFmpeg. I'd spawn a hidden `<video>` element, and then play that back. Then you can call [captureStream](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream), and then create a MediaStreamTrackProcessor:
```ts
new MediaStreamTrackProcessor({ track: videoTrack });
```
Then, similarly to how I do in my demo, you'll get individual `VideoFrame` instances out! Which is great, because those hold unencoded video data which you can then simply reencode as usual and pipe into `mp4-muxer`. You'll need to make sure to iron out the details to make sure you don't miss any frames in the input video, and you may need to have some custom timestamp logic, but this should still give you good results! FFmpeg should be the last resort :)

**Comment by nuthinking** [comment]
So, no way to use `MediaStreamTrackProcessor` directly with a `MediaRecorder`? The playback capture is way too hackish :)

**Comment by Vanilagy** [comment]
Oh yeah wait I read over that. Why don't you record directly into mp4? Or simply skip MediaRecorder altogether?

**Comment by nuthinking** [comment]
Yeah, I guess WebCodecs performances are comparable to `MediaRecorder`. Hence if a recording is smooth with `MediaRecorder`, it should also be smooth with `VideoEncoder` 😅

**Comment by Vanilagy** [comment]
What are you recording?

**Comment by nuthinking** [comment]
Yes, only thing I had to handle was that the canvas, on some computers, render at much higher fps than the video I wanted to export. Thanks for the idea!
