### ISSUE TITLE
Planning to add a demuxer anytime soon?

### ISSUE THREAD

**Issue by pabloruizetc** [Vanilagy/mp4-muxer#41]
Just wondering if there are any plans to throw in a demultiplexer feature into the library at some point. Got anything like that on the roadmap?

**Comment by Vanilagy** [comment]
It is on my mind, yes, but it would not be thrown into this library. I wonder what the demand for a demuxer is! I haven't needed it personally, but my guess would be that `VideoDecoder` is completely useless without one.

What do you need one for?

Demuxing comes with its own set of challenges, since suddenly you're dealing with arbitrary input. Different MP4 files, creates by different muxers and formatted differently, across different videos. Let alone malicious files that are crafted to crash software! So, definitely not trivial, even though I could probably throw together a naive MP4 parser in a weekend. I'm very familiar with the format now :)

**Comment by Vanilagy** [comment]
Not quite sure what you mean. By which process are you getting your VideoFrames?

**Comment by Vanilagy** [comment]
Not sure they use ffmpeg for demuxing!

**Comment by ivanjaros** [comment]
Hi, i need to add authentication header to a GET request for a standard video file url. Which means i have no other way but to use MediaSource. Can this library support this? Essentially standard behavior as the browser but adds the ability to provide my own url and options to the fetch() method. This does not require demuxing, only muxing...i think. Can this library work in this case?

**Comment by Vanilagy** [comment]
@ivanjaros I'm not sure what you mean. This library has nothing to do with HTTP!

**Comment by Vanilagy** [comment]
Closing this issue for now, if I ever make a demuxer I'll make sure to drop an update.
