### ISSUE TITLE
Muxer.finalize() never returns anything

### ISSUE THREAD

**Issue by jlecordier** [Vanilagy/mp4-muxer#5]
Hi,

I think there is a mismatch between the doc and the source code.

The doc states : `@returns Should you have used `target: 'buffer'` in the configuration options, this method will return the buffer containing the final MP4 file.`

But no `return` is to be found in the source code : https://github.com/Vanilagy/mp4-muxer/blob/8371be1feacd57918016b37c6b9baa44a0de190b/src/muxer.ts#LL389C7-L389C7

This also brings the question : why is the doc not in the source code but in a different `.d.ts` file ?

**Comment by Vanilagy** [comment]
Thank you for spotting that! The comment is a leftover from the way the API worked previously, and forgot to change it. To your question, which source code do you mean? The `mp4-muxer.js` build file or all of the source files in the `src` directory?

**Comment by jlecordier** [comment]
I am talking about the ts files in the src directory 😉

**Comment by LiubomyrB** [comment]
@Vanilagy How do you check if the recording was finalized? I need it to avoid race conditions when recording fragmented mp4. Currently, I do the following:
1. start recording;
2. save raw chunks from muxer to Origin Private File System;
3. stop recording;
4. muxer.finalize();
5. merge those chunks that were saved in step 2;
6. downloadBlob();
But the size of the file is 28 B. The problem is that I should wait for the final chunk from Muxer to start merging all chunks into one blob. I don't know how to check if the final chunk was produced and whether it was the final chunk.

If to call downloadBlob after timeout, then it will work fine:
...
6. setTimeout(downloadBlob, 3000);

But probably this workaround will not work with large recordings. Muxer instance has private "#finalized" property but I cannot access it from outside.

**Comment by Vanilagy** [comment]
The muxer is finalized when `finalize` returns. By that I mean, StreamTarget will not be receiving any more data after `finalize` has returned. If the size of the file is 28 B, that tells me you're either saving the chunks wrong or are not saving all chunks.

**Comment by LiubomyrB** [comment]
Thank you for answering. The problem was that the last onData callback (that contains mfra box) was fired after I started merging all chunks into one. I solved it by checking whether the chunk from the last onData callback contains "mfra". If it doesn't contain, then I wait until it contains - then I know for sure that this chunk is the last and I can proceed with merging and downloading.

**Comment by Vanilagy** [comment]
Why don't you just start the merging after `finalize` returns?

**Comment by LiubomyrB** [comment]
I don't have all chunks when a call finalize() (I have all chunks but last). Seems onData callback (of Mp4Muxer.StreamTarget) is fired asynchronously, so I should wait for a split second for onData callback with the last chunk.

**Comment by Vanilagy** [comment]
No, `onData` is called synchronously. There's no async code anywhere in this library! How does your code look?

**Comment by LiubomyrB** [comment]
Sorry, you are right. I was trying to merge all chunks after onData callback was fired with the last chunk but before this chunk was saved to OPFS.
```
muxer = new Mp4Muxer.Muxer({
	target: new Mp4Muxer.StreamTarget({
		onData: function (buffer) {
			console.log('chunk produced')
			chunkCounter++;
			saveTempChunk(buffer, fileName + '_' + chunkCounter).then(function (chunkHandle) {
				console.log('chunk saved');
				if (chunkHandle) chunkHandles.push(chunkHandle);
			});
		}

	}),
	video: {
		codec: 'avc',
		width: canvas.width,
		height: canvas.height
	},
	fastStart: 'fragmented',
	firstTimestampBehavior: 'offset'
});
```
