### ISSUE TITLE
Use MediaStream from webaudio, rather than mic input.

### ISSUE THREAD

**Issue by acamposuribe** [Vanilagy/mp4-muxer#53]
Hi!

I'm trying to record my canvas as well as a mediastream that comes from webaudio (tonejs, to be more precise).
I have extracted the audiotrack from the audiocontext, and fed it to the MediaStreamTrackProcessor as you do in your example. However, the AudioEncoder doesn't work, it throws:

`DOMException: Input audio buffer is incompatible with codec parameters`

This is full relevant code:

````
const audioStream = Tone.getContext().createMediaStreamDestination();
const audioTrack = audioStream.stream.getAudioTracks()[0];
const audioSampleRate = 48000;

audioEncoder = new AudioEncoder({
      output: (chunk, meta) => muxer.addAudioChunk(chunk, meta),
      error: (e) => console.error(e),
    });
    audioEncoder.configure({
      codec: "mp4a.40.2",
      numberOfChannels: 1,
      sampleRate: audioSampleRate,
      bitrate: 128000,
    });

let trackProcessor = new MediaStreamTrackProcessor({ track: audioTrack });
    let consumer = new WritableStream({
      write(audioData) {
        if (!recording) return;
        audioEncoder.encode(audioData);
        audioData.close();
      },
    });

trackProcessor.readable.pipeTo(consumer);
````

Thanks in advance!

**Comment by Vanilagy** [comment]
Are you dealing with real-time data? Or do you, at the start of recording, already know how everything will play out? Because in that case, you should not use a `MediaStreamTrackProcessor`. Wrong tool for the job! You can use an [offline context](https://tonejs.github.io/docs/15.0.4/classes/OfflineContext.html) to render the entire out as fast as possible, then create an [AudioData](https://developer.mozilla.org/en-US/docs/Web/API/AudioData) from the resulting AudioBuffer, then pipe that into the encoder all at once.

If you do happen to be working with real-time data, you can consider using a ScriptProcessorNode to extract audio data from your context. If this doesn't work, the `MediaStreamTrackProcessor` should still be okay. Regarding the error, I think it's very clear. Check the [sampleRate](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/sampleRate) and the [channel count](https://developer.mozilla.org/en-US/docs/Web/API/AudioDestinationNode/maxChannelCount) on your audio context, and try to match that with the encoder.

Anyway, I'm closing this issue since it's not related to this libray directly. But good luck!

**Comment by acamposuribe** [comment]
Thx for the tips!
