### ISSUE TITLE
any possibility to add vp9 and opus ?

### ISSUE THREAD

**Issue by 0-mandrixx-0** [Vanilagy/mp4-muxer#8]
I made some extensive tests for a project that involves encoding and decoding with webcodecs, and I need it to work on mobile phones. the mp4a codec is not yet supported on android chrome so using opus is the only option.

I've tried muxing vp9 and opus and it works nicely with webm-muxer, but I can't demux the output of webm-muxer with jswebm. jswebm fails for most webm videos (track data element not found, invalid file size, Invalid Seek Formatting, etc) I've been trying, but works for the big bad bunny demo video. project has not been updated since a while and I couldn't find a better option.

I don't know how hard it would be to add support for vp9 and opus to mp4-muxer. it would be a nice addition so along with mp4box, it would cover all webcodec needs.

the following reference show vp9 and opus are valid codecs for mp4 :
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs

I will meanwhile craft a mp4 with vp9 and opus to check if it can be demuxed correctly with mp4box

regards,

**Comment by Vanilagy** [comment]
Interesting! First of all, I'm surprised that you say MP4A isn't widely supported. It's AAC, and that has absolute crazy support since it's used in like almost every MP4 file ever.

But, good to know MP4 supports VP9. I mean, it does make sense, MP4 has a very general format, but AVC (and maybe HEVC) is definitely the biggie here when it comes to codecs. The MDN page even says that AV1 works with MP4, which we could also try. 

I don't think adding VP9 and Opus support to this library should be too hard; all I'll need for that is a sample MP4-with-VP9-and-Opus file so I can see which blocks are being used. Do you have any of those around? And, while we're at it, do you have one with AV1?

Also a shame to see that jswebm doesn't seem to understand my WebM files. That stuff always confuses me since either this is a jswebm bug, or the files I'm creating are malformed. However, my WebM files seem to play pretty well pretty much everywhere, and MKVToolNix has no trouble reading them.

**Comment by 0-mandrixx-0** [comment]
I crafted two sample video files with ffmpeg :
https://keny.toys/tmp/testvp9opus.mp4
https://keny.toys/tmp/testav1opus.mp4

I read somewhere there's a milestone set for android aac support in webcodec for chrome 118. I hope they can add it.
AV1 is available in webcodecs on android and desktop but it just crashes the browser when I try it.

**Comment by Vanilagy** [comment]
Got around to implementing the new codecs - a new version's out. Would be awesome if you could play with it a bit :)

**Comment by 0-mandrixx-0** [comment]
great will try to implement it next week and at least make a desktop test. ty !

**Comment by 0-mandrixx-0** [comment]
did some first test. I managed to get a working video with vp9 and opus from webcodecs chunks. it plays fine with chrome but can't decode it with mp4box. I have the following :
mp4box.all.js:589  Uncaught (in promise) RangeError: Invalid typed array length: -4
    at new Uint8Array (<anonymous>)
    at DataStream.readUint8Array (mp4box.all.js:589:13)
    at BoxParser.FullBox.parseDataAndRewind (mp4box.all.js:2548:21)
    
I'll try to dig in this when I can
