### ISSUE TITLE
Feature request: Non-integer framerates

### ISSUE THREAD

**Issue by mmamedel** [Vanilagy/mp4-muxer#81]
Hello,
Amazing work with this library. Thank you!
The reason for this issue is that I am currently getting this error message:
`Invalid video frame rate: 29.97002997002997. Must be a positive integer.`

Since 29.97 is a very common framerate I just wonder if this is a feature that could be included.
Thank you,
**_Mateus_**

**Comment by Tianj0o** [comment]
hi mmamedel , The 29.97 fps rate exists mainly for historical compatibility reasons, particularly in video standards like NTSC. However, it's important to note that browser-based encoders typically require the frame rate to be an integer, which is why this specific frame rate isn't directly supported. [More info here](https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder/configure).

I did try removing the code that forces the frame rate to be an integer and set it to 29.97, but the final video ended up having a frame rate of 29. This is because, as mentioned earlier, browser-based encoders (such as those commonly used in web video processing) require the frame rate to be an integer.

Hope this helps clarify the situation

**Comment by Vanilagy** [comment]
@mmamedel Good question.

In this library, setting the `frameRate` field is optional. Your first option would be to simply not set it and simply provide chunks that have timestamps that are aligned to 29.97 FPS. The timestamps in the resulting MP4 won't be exact-exact, but they will differ by at most 1/115200 seconds, since 57600 is the default internal timescale and timestamps are rounded to fit this timescale.

If you want them to be exact, you'll need to supply an integer frame rate that is divisble by your desired frame rate. Since you're targeting 29.97 FPS, you should set `frameRate` to `30000`. Since 29.97 FPS is actually `30000/1001` FPS, using a frame rate of `30000` (which sets the internal timescale to `30000`) will allow you to perfectly represent your desired frame rate (of course, you'll still need to set the incoming timestamps correctly).

The reasoning given by @Tianj0o is incorrect. The encoders don't intrinsically care about frame rate, as it's irrelevant to the encoding/decoding process. The reason that using 29.97 results in a frame rate of 29 is because the code that writes the timescale into the output file writes it as an unsigned 32-bit integer, and that just implicitly truncates any non-integer you give it.

Hope this clears things up.

**Comment by Tianj0o** [comment]
Thanks for your explanation! I’ve modified the code and got 29.97fps video. I’ve also learned a lot about timescale in the process . there’s still much more to learn
